# security-action.yml
name: "Security Action"

on:
  push:
    branches: [ '*' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v4

      - name: CodeQL Scan
        uses: NicholasEllul/Appsec-CodeQL@main
        with:
          paths_ignored: 'data,test'
          queries: '[{ "name": "Juiceshop qls pack", "uses": "./qls-packs/juiceshop.qls"}]'
          languages: "javascript-typescript, typescript"
          repo: ${{ github.repository }}
