# security-action.yml
name: "Code Scanning"

on:
  workflow_dispatch:
    inputs:
      paths_ignored:
        description: 'Comma-separated list of paths to ignore in scan'
        required: true
        default: 'path/to/ignore'
      rules_ignored:
        description: 'Comma-separated list of rule IDs to ignore'
        required: true
        default: 'rule1,rule2'
  # push:
  #   branches: [ '*' ]
  # pull_request:
  #   branches: [ '*' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v4

      - name: witmicko Security Code Scanner
        uses: witmicko/Security-Code-Scanner@main
        with:
          paths_ignored: ${{ inputs.paths_ignored }}
          rules_ignored: ${{ inputs.rules_ignored }}
          