# security-action.yml
name: "Security Action"

on:
  push:
    branches: [ '*' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:   
      - name: Security Code Scanner
        uses: NicholasEllul/Security-Code-Scanner@main
        with:
          paths_ignored: 'data,test'
          languages: "javascript-typescript, typescript"
          repo: ${{ github.repository }}
