# security-action.yml
name: "Security Action"

on:
  push:
    branches: [ '*' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"
