name: Security Scan

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo to scan
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        
    - name: Security Code Scanner
      uses: MetaMask/Security-Code-Scanner@de20399f9116bd2f26c8af54a238687ae2adde2e
      with:
        repo: ${{ github.repository }}
