# security-action.yml
name: "Security Action"
inputs:
  paths_ignored:
    description: 'Comma delimitted paths to ignore during scan' 
    required: false
  rules_excluded:
    description: 'Comma delimitted IDs of rules to exclude' 
    required: false

on:
  workflow_dispatch:

  # push:
  #   branches: [ '*' ]
  # pull_request:
  #   branches: [ '*' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:   
      - name: witmicko Security Code Scanner
        uses: witmicko/Security-Code-Scanner@main
        with:
          repo: ${{ github.repository }}
          paths_ignored: ${{ inputs.paths_ignored }}
          rules_excluded: ${{ inputs.rules_excluded }}
          