# security-action.yml
name: "Security Action"

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v2

      - name: NicholasEllul Security Code Scanner
        uses: NicholasEllul/Security-Code-Scanner@main
        with:
          paths_ignored: 'data,test'
          queries: '[{ "name": "Juiceshop qls pack", "uses": "./qls-packs/juiceshop.qls"}]'
          languages: "javascript-typescript, typescript"
          repo: ${{ github.repository }}
      - name: Output repository
        run: echo "The repository is ${{ github.repository }}"
