# security-action.yml
name: "Security Action"


on:
  workflow_dispatch:
    inputs:
      paths_ignored:
        description: 'Comma delimited paths to ignore during scan' 
        required: false
      rules_excluded:
        description: 'Comma delimited IDs of rules to exclude' 
        required: false

  # push:
  #   branches: [ '*' ]
  # pull_request:
  #   branches: [ '*' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:   
      - name: witmicko Security Code Scanner
        uses: witmicko/Security-Code-Scanner@main
        with:
          repo: ${{ github.repository }}
          paths_ignored: ${{ inputs.paths_ignored }}
          rules_excluded: ${{ inputs.rules_excluded }}
          